# Generated by Django 4.2.4 on 2023-08-11 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_session_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
