# Generated by Django 4.2.4 on 2023-08-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='start_time',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='speciality',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
