# Generated by Django 4.2.4 on 2023-08-10 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_useraccount_end_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
        migrations.DeleteModel(
            name='Mother',
        ),
        migrations.DeleteModel(
            name='Specialist',
        ),
    ]
